# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-05 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='article',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
