# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-05 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20180305_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-time']},
        ),
    ]
